############################
# HLint Configuration File #
############################

# See https://github.com/ndmitchell/hlint

# Specify additional command line arguments
- arguments: [--color, --cpp-simple, -XQuasiQuotes]

#######################
# MODULE RESTRICTIONS #
#######################

- modules:
  - {name: Control.Monad.Error, within: []}
  - {name: Data.Aeson, as: Aeson}
  - {name: Data.ByteString, as: B }
  - {name: Data.ByteString.Char8, as: BC }
  - {name: Data.ByteString.Lazy, as: BL }
  - {name: Data.ByteString.Lazy.Char8, as: BLC }
  - {name: Data.ByteString.Base64, as: Base64 }
  - {name: Data.Text, as: T }
  - {name: Data.Text.Lazy, as: TL }
  - {name: Data.Text.Encoding, as: TE }
  - {name: Data.Time, as: Time }

##########################
# EXTENSION RESTRICTIONS #
##########################

- extensions:
  - default: false # All extension are banned by default
  - name: # Only these listed extensions can be used
      - OverloadedStrings
      - RankNTypes
      - TupleSections

################
# CUSTOM RULES #
################

# Replace a $ b $ c with a . b $ c
- group: {name: dollar, enabled: true}

# Generalise map to fmap, ++ to <>
- group: {name: generalise, enabled: true}

# Warn about redundant do:
- warn: {name: Redundant do}
